// Interface for PickupAddress
export interface PickupAddress {
  name: string;
  mobile: string;
  pincode: string;
  address: string;
  locality: string;
  city: string;
  state: string;
}

// Interface for BankDetails
export interface BankDetails {
  accountNumber: string;
  ifscCode: string;
  accountHolderName: string;
}

// Interface for BusinessDetails
export interface BusinessDetails {
  businessName: string;
  // Additional business details properties can be added here
}
export interface Seller {
  id?: number; // Optional: Unique identifier for the seller
  mobile: string; // Mobile number of the seller
  otp: string; // One-Time Password for verification
  GSTIN: string; // Goods and Services Tax Identification Number
  pickupAddress: PickupAddress; // Seller's pickup address, referencing the PickupAddress interface
  bankDetails: BankDetails; // Seller's bank details, referencing the BankDetails interface
  sellerName: string; // Name of the seller
  email: string; // Email address of the seller
  businessDetails: BusinessDetails; // Seller's business details, referencing the BusinessDetails interface
  password: string; // Password for seller login
  accountStatus?: string; // Optional: Status of the seller's account (e.g., "Active", "Pending", "Suspended")
}

// Interface for PickupAddress
// Interface for SellerReport
export interface SellerReport {
  id: number; // Unique identifier for the report
  seller: Seller; // The seller associated with this report, referencing the Seller interface
  totalEarnings: number; // Total revenue generated by the seller
  totalSales: number; // Total number of sales made
  totalRefunds: number; // Total value of refunds processed
  totalTax: number; // Total tax collected
  netEarnings: number; // Net earnings after deductions
  totalOrders: number; // Total number of orders received
  canceledOrders: number; // Total number of canceled orders
  totalTransactions: number; // Total number of transactions
}
